name: "test"

services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html

  node:
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    command: npm run dev
